trigger:
  - main
  - dev
  - azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: pipeline-variables

# For more info on schema definition: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-compose-v0?view=azure-pipelines
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: Build Docker Images
        steps:
          - task: DockerCompose@0
            inputs:
              action: Build services
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: apps/object-storage-solution/docker-compose.yml
              projectName: $(Build.Repository.Name)
              qualifyImageNames: true
              additionalImageTags: $(Build.BuildId)
  - stage: Push
    jobs:
      - job: PushJob
        displayName: Push Docker Images
        steps:
          - task: DockerCompose@0
            displayName: Push services
            inputs:
              action: Push services
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
              azureContainerRegistry: $(azureContainerRegistry)
              dockerComposeFile: docker-compose.yml
              additionalDockerComposeFiles: apps/object-storage-solution/docker-compose.yml
              projectName: $(Build.Repository.Name)
              qualifyImageNames: true
              additionalImageTags: $(Build.BuildId)
