name: research-platform

services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_USER=/run/secrets/db_username
      - POSTGRES_DB=${DB_NAME:-db}
    entrypoint: /usr/local/bin/database_entrypoint.sh
    volumes:
      - ${SSL_DIR:?}:/ssl
      - ./scripts/database_entrypoint.sh:/usr/local/bin/database_entrypoint.sh
    secrets:
      - db_username
      - db_password
    networks:
      - db_network

  backend:
    build:
      args:
        APP: backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - 3001:3001
    env_file:
      - apps/backend/.env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-db}
      - DB_PASSWORD=/run/secrets/db_password
      - DB_USERNAME=/run/secrets/db_username
    secrets:
      - db_username
      - db_password
    networks:
      - db_network
      - es_network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - type: tmpfs
        target: /usr/share/elasticsearch/data
        tmpfs:
          size: "1000000"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es_network

secrets:
  db_password:
    file: ${SECRETS_DIR:?}/db_password.txt
  db_username:
    file: ${SECRETS_DIR:?}/db_username.txt

networks:
  db_network:
  es_network:
